# Generated by Django 3.2.14 on 2025-12-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20251218_0159'),
        ('orders', '0015_add_peer_product_to_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='peer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.peertopeerproduct', verbose_name='Article C2C'),
        ),
    ]
