# Generated by Django 3.2.14 on 2025-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20220814_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_province', models.CharField(max_length=10, unique=True)),
                ('name_province', models.CharField(max_length=100)),
                ('capitale_province', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name_province'],
            },
        ),
    ]
