# Generated by Django 3.2.14 on 2025-08-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
