# Generated by Django 3.2.14 on 2025-08-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
