# Generated by Django 3.2.14 on 2025-12-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_payment_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderdetailssupplier',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
