# Generated by Django 3.2.14 on 2026-01-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderdetails_peer_product'),
        ('orders', '0037_remove_paymob_fields'),
    ]

    operations = [
    ]
