# Generated by Django 5.1.15 on 2026-04-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_payment_service_fee_b2cdeliveryverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2cdeliveryverification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Traçabilité livraison B2C (codes)', 'verbose_name_plural': 'B2C - Traçabilité livraison (codes)'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-id',), 'verbose_name': 'Coupon B2C', 'verbose_name_plural': 'B2C - Coupons'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Commande B2C (globale)', 'verbose_name_plural': 'B2C - Suivi cycle de commande'},
        ),
        migrations.AlterModelOptions(
            name='ordersupplier',
            options={'ordering': ('-id',), 'verbose_name': 'Commande B2C par magasin', 'verbose_name_plural': 'B2C - Commandes par magasin'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-id',), 'verbose_name': 'Paiement commande B2C', 'verbose_name_plural': 'B2C - Paiements commande'},
        ),
    ]
