# Generated by Django 3.2.14 on 2025-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_vendorpayments_id'),
    ]

    operations = [
    ]
