# Generated by Django 3.2.14 on 2025-12-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_singpay_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayments',
            options={'ordering': ('-id',), 'verbose_name': 'Paiement vendeur', 'verbose_name_plural': 'Paiements vendeurs'},
        ),
        migrations.RemoveIndex(
            model_name='singpaytransaction',
            name='payments_si_transac_8a1b2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='singpaytransaction',
            name='payments_si_interna_9c2d3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='singpaytransaction',
            name='payments_si_status_4d5e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='singpaytransaction',
            name='payments_si_user_id_7g8h9i_idx',
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='fee',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Paypal', 'Paypal'), ('SingPay', 'SingPay')], default='Bank', max_length=15, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='request_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Montant demandé'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Refunded', 'Refunded')], default='Pending', max_length=13, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profil vendeur'),
        ),
        migrations.AddIndex(
            model_name='singpaytransaction',
            index=models.Index(fields=['transaction_id'], name='payments_si_transac_d4017e_idx'),
        ),
        migrations.AddIndex(
            model_name='singpaytransaction',
            index=models.Index(fields=['internal_order_id'], name='payments_si_interna_9f00cd_idx'),
        ),
        migrations.AddIndex(
            model_name='singpaytransaction',
            index=models.Index(fields=['status'], name='payments_si_status_617f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='singpaytransaction',
            index=models.Index(fields=['user'], name='payments_si_user_id_70ea0c_idx'),
        ),
    ]
