# Generated by Django 3.2.14 on 2025-12-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20251218_0159'),
        ('payments', '0010_auto_20251205_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singpaytransaction',
            name='peer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.peertopeerproduct', verbose_name='Article C2C'),
        ),
        migrations.AlterField(
            model_name='singpaytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Paiement de commande'), ('boost_payment', 'Paiement boost produit'), ('subscription_payment', 'Paiement abonnement'), ('c2c_payment', 'Paiement C2C'), ('commission_payment', 'Paiement commission')], max_length=30, verbose_name='Type de transaction'),
        ),
    ]
