# Generated by Django 3.2.14 on 2026-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_add_escrow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayments',
            name='method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('SingPay', 'SingPay')], default='Bank', max_length=15, verbose_name='Méthode de paiement'),
        ),
    ]
