# Generated by Django 3.2.14 on 2026-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_vendorpayments_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singpaytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Paiement de commande'), ('boost_payment', 'Paiement boost produit'), ('subscription_payment', 'Paiement abonnement'), ('c2c_payment', 'Paiement C2C'), ('commission_payment', 'Paiement commission'), ('cash_service_fee', 'Frais de service paiement à la livraison')], max_length=30, verbose_name='Type de transaction'),
        ),
    ]
