# Generated by Django 5.1.15 on 2026-04-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220814_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousels'},
        ),
        migrations.AlterModelOptions(
            name='headtextad',
            options={'verbose_name': 'Head Text Ad', 'verbose_name_plural': 'Head Text Ads'},
        ),
        migrations.AlterModelOptions(
            name='homeaddaily',
            options={'verbose_name': 'Home Ad Daily', 'verbose_name_plural': 'Home Ads Daily'},
        ),
        migrations.AlterModelOptions(
            name='homeaddealtime',
            options={'verbose_name': 'Home Ad Daily', 'verbose_name_plural': 'Home Ads Daily'},
        ),
        migrations.AlterModelOptions(
            name='homeadmiddlebar',
            options={'verbose_name': 'Home Ad Middlebar', 'verbose_name_plural': 'Home Ads Middlebar'},
        ),
        migrations.AlterModelOptions(
            name='homeadsidebar',
            options={'verbose_name': 'Home Ad Sidebar', 'verbose_name_plural': 'Home Ads Sidebar'},
        ),
        migrations.AlterModelOptions(
            name='homeadsupplier',
            options={'verbose_name': 'Home Ad Supplier', 'verbose_name_plural': 'Home Ads Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='hotdealad',
            options={'verbose_name': 'Hot Deal Ad', 'verbose_name_plural': 'Hot Deal Ads'},
        ),
        migrations.AlterModelOptions(
            name='shopadsidebar',
            options={'verbose_name': 'Shop Ad Sidebar', 'verbose_name_plural': 'Shop Ads Sidebar'},
        ),
        migrations.AlterModelOptions(
            name='vendordetailsadimage',
            options={'verbose_name': 'Vendor Details Ad Image', 'verbose_name_plural': 'Vendors Details Ad Image'},
        ),
    ]
