"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis .env
# Le fichier .env doit être créé à la racine du projet (gabomazone-app/.env)
# python-decouple cherche automatiquement le fichier .env à la racine du projet


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mysecret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "51.91.255.215",
    "gabomazone.com",
    "www.gabomazone.com",
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    # General use templates & template tags (should appear first)
    'adminlte3',
    # Optional: Django admin theme (must be before django.contrib.admin)
    'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'captcha',
    'currencies',
    'home',
    'categories',
    'products',
    'accounts',
    'orders',
    'suppliers',
    'supplier_panel',
    'ckeditor',
    'crispy_forms',
    # 'FAQ',
    # 'newsletters',
    #'blog',
    #'reports',
    'settings',
    'contact',
    'pages',
    'payments',
    'c2c',  # Module C2C
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'categories.context_processors.category_obj',
                'products.context_processors.new_products_obj',
                'orders.context_processors.orders_cart_obj',
                'products.context_processors.wishlist_count',
                'products.context_processors.messages_count',
                'home.context_processors.DealTime_obj',
                'home.context_processors.vendor_details_ad_image',
                'home.context_processors.shop_ad_sidebar',
                'home.context_processors.hot_deal_ad',
                'home.context_processors.head_text_ad',
                'settings.context_processors.socail_links_settings',
                'settings.context_processors.contact_info_settings',
                'settings.context_processors.support_number_settings',
                'settings.context_processors.site_settings',
                'pages.context_processors.pages_list_obj',

            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nestali',
#         'USER': 'nestali',
#         'PASSWORD': 'nestali123!@#',
#         'HOST': 'localhost',
#         'PORT':'',
#         'OPTIONS': {
#         'sql_mode': 'traditional',
#     }
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

###DEFAULT_CURRENCY##
DEFAULT_CURRENCY = 'FCFA'

# Internationalization - French only
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Libreville'

USE_I18N = False

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Image',
                'Textarea', 'Select', 'Button', 'HiddenField']

        ]
    }
}

CRISPY_TEMPLATE_PACK = 'uni_form'

# #Smtp Email for recovery password
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
#SENDGRID_API_KEY = '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'
SENDGRID_API_KEY = 'UseTheAbove_SENDGRID_API_KEY_ForThisOneIsFake'
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
EMAIL_SENDGRID = "selemhamed2016@gmail.com"


        ## SingPay account ##
        # Configuration SingPay selon la documentation: https://client.singpay.ga/doc/reference/index.html
        # Les clés API sont chargées depuis le fichier .env pour la sécurité
        # Voir .env.example pour le format attendu
SINGPAY_API_KEY = config('SINGPAY_API_KEY', default='')
SINGPAY_API_SECRET = config('SINGPAY_API_SECRET', default='')
SINGPAY_MERCHANT_ID = config('SINGPAY_MERCHANT_ID', default='')
SINGPAY_DISBURSEMENT_ID = config('SINGPAY_DISBURSEMENT_ID', default='')  # ID portefeuille pour les virements (disbursement)
SINGPAY_ENVIRONMENT = config('SINGPAY_ENVIRONMENT', default='sandbox')  # 'sandbox' ou 'production'

# Domaine de production pour les URLs de callback SingPay
# Les callbacks doivent être accessibles publiquement depuis Internet
SINGPAY_PRODUCTION_DOMAIN = config('SINGPAY_PRODUCTION_DOMAIN', default='gabomazone.pythonanywhere.com')
