"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis .env
# Le fichier .env doit être créé à la racine du projet (gabomazone-app/.env)
# python-decouple cherche automatiquement le fichier .env à la racine du projet


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Garde de sécurité : SECRET_KEY obligatoire en production
if not DEBUG and (not SECRET_KEY or 'insecure' in SECRET_KEY):
    raise ImproperlyConfigured(
        "SECRET_KEY doit être défini via la variable d'environnement SECRET_KEY en production. "
        "Voir gabomazone-app/.env.example"
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv()) + [
    "51.91.255.215",
    "gabomazone.com",
    "www.gabomazone.com",
]

# Application definition

INSTALLED_APPS = [
    # General use templates & template tags (should appear first)
    'adminlte3',
    # Optional: Django admin theme (must be before django.contrib.admin)
    'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'whitenoise.runserver_nostatic',
    'captcha',
    'currencies',
    'home',
    'categories',
    'products',
    'accounts',
    'orders',
    'suppliers',
    'supplier_panel',
    'ckeditor',
    'crispy_forms',
    # 'FAQ',
    # 'newsletters',
    #'blog',
    #'reports',
    'settings',
    'contact',
    'pages',
    'payments',
    'c2c',  # Module C2C
    'django_ratelimit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'categories.context_processors.category_obj',
                'products.context_processors.new_products_obj',
                'orders.context_processors.orders_cart_obj',
                'products.context_processors.wishlist_count',
                'products.context_processors.messages_count',
                'products.context_processors.pending_c2c_meeting_for_modal',
                'home.context_processors.DealTime_obj',
                'home.context_processors.vendor_details_ad_image',
                'home.context_processors.shop_ad_sidebar',
                'home.context_processors.hot_deal_ad',
                'home.context_processors.head_text_ad',
                'settings.context_processors.socail_links_settings',
                'settings.context_processors.contact_info_settings',
                'settings.context_processors.support_number_settings',
                'settings.context_processors.site_settings',
                'pages.context_processors.pages_list_obj',

            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if config('USE_SQLITE', default='false').lower() == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB', default='gabomazone'),
            'USER': config('POSTGRES_USER', default='gabomazone'),
            'PASSWORD': config('POSTGRES_PASSWORD', default=''),
            'HOST': config('POSTGRES_HOST', default='db'),
            'PORT': config('POSTGRES_PORT', default='5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

###DEFAULT_CURRENCY##
DEFAULT_CURRENCY = 'FCFA'

# Internationalization - French only
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Libreville'

USE_I18N = False

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Désactiver chmod sur les uploads : les volumes Docker (et certains FS) rejettent
# le chmod même avec permissions 777 (Operation not permitted sur os.chmod)
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Image',
                'Textarea', 'Select', 'Button', 'HiddenField']

        ]
    }
}

CRISPY_TEMPLATE_PACK = 'uni_form'

# #Smtp Email for recovery password
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
EMAIL_SENDGRID = config('EMAIL_SENDGRID', default='contact@gabomazone.com')


        ## SingPay account ##
        # Configuration SingPay selon la documentation: https://client.singpay.ga/doc/reference/index.html
        # Les clés API sont chargées depuis le fichier .env pour la sécurité
        # Voir .env.example pour le format attendu
SINGPAY_API_KEY = config('SINGPAY_API_KEY', default='')
SINGPAY_API_SECRET = config('SINGPAY_API_SECRET', default='')
SINGPAY_MERCHANT_ID = config('SINGPAY_MERCHANT_ID', default='')
SINGPAY_DISBURSEMENT_ID = config('SINGPAY_DISBURSEMENT_ID', default='')  # ID portefeuille pour les virements (disbursement)
SINGPAY_ENVIRONMENT = config('SINGPAY_ENVIRONMENT', default='sandbox')  # 'sandbox' ou 'production'

# Domaine de production pour les URLs de callback SingPay
# Les callbacks doivent être accessibles publiquement depuis Internet
SINGPAY_PRODUCTION_DOMAIN = config('SINGPAY_PRODUCTION_DOMAIN', default='gabomazone.pythonanywhere.com')


# =============================================================================
# SÉCURITÉ HTTP — Headers de sécurité pour la production
# =============================================================================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Avec DEBUG=False sur du HTTP local, les cookies Secure ne sont pas conservés par le
# navigateur → échecs CSRF sur /login/ (403 « token from POST incorrect » ou similaire).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True

# Origines autorisées pour la vérification Referer/Origin (Django 4+). En prod, renseigner
# CSRF_TRUSTED_ORIGINS dans .env (ex. https://gabomazone.com,https://www.gabomazone.com).
_csrf_trusted = [o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv()) if o and str(o).strip()]
if DEBUG:
    for _origin in (
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://[::1]:8000',
    ):
        if _origin not in _csrf_trusted:
            _csrf_trusted.append(_origin)
CSRF_TRUSTED_ORIGINS = _csrf_trusted

# =============================================================================
# SESSIONS — Durée de vie et nettoyage
# =============================================================================
SESSION_COOKIE_AGE = 1209600  # 2 semaines
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False

# =============================================================================
# CACHE & SESSIONS REDIS — Activé si REDIS_URL est défini
# =============================================================================
_REDIS_URL = config('REDIS_URL', default='')
if _REDIS_URL:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
        }
    }

# =============================================================================
# CELERY — Queue de tâches asynchrones
# =============================================================================
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://redis:6379/1')
CELERY_BEAT_SCHEDULE = {
    'expire-c2c-intents': {
        'task': 'c2c.tasks.expire_old_intents',
        'schedule': 3600.0,
    },
    'reconcile-pending-payments': {
        'task': 'payments.tasks.reconcile_pending_transactions',
        'schedule': 900.0,
    },
    'cleanup-sessions': {
        'task': 'accounts.tasks.cleanup_expired_sessions',
        'schedule': 86400.0,
    },
}


# =============================================================================
# LOGGING — structured logging for traceability
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'gabomazone.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'accounts': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'orders':   {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'payments': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'products': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'c2c':      {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'categories': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'home':     {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}
