# Generated by Django 3.2.14 on 2025-12-08 17:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0010_auto_20251205_1702'),
        ('accounts', '0018_alter_peertopeerordernotification_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2COrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix final')),
                ('buyer_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission acheteur')),
                ('seller_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission vendeur')),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission plateforme')),
                ('seller_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net vendeur')),
                ('buyer_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total à payer')),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('paid', 'Payé'), ('pending_delivery', 'Livraison en attente'), ('delivered', 'Livré'), ('verified', 'Vérifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('disputed', 'Litige')], default='pending_payment', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c2c_orders_bought', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2c_orders', to='payments.singpaytransaction', verbose_name='Transaction de paiement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c2c_orders', to='accounts.peertopeerproduct', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commande C2C',
                'verbose_name_plural': 'Commandes C2C',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2c_buyer_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.90'), help_text="Pourcentage de commission prélevé sur l'acheteur pour les transactions C2C", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission acheteur C2C (%)')),
                ('c2c_seller_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('9.90'), help_text='Pourcentage de commission prélevé sur le vendeur pour les transactions C2C', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission vendeur C2C (%)')),
                ('b2c_buyer_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Pourcentage de commission prélevé sur l'acheteur pour les transactions B2C", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission acheteur B2C (%)')),
                ('b2c_seller_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage de commission prélevé sur le vendeur pour les transactions B2C', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission vendeur B2C (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('negotiating', 'En négociation'), ('agreed', 'Accord trouvé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix initial')),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix négocié')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix final accepté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('agreed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'accord")),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('seller_notified', models.BooleanField(default=False, verbose_name='Vendeur notifié')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_purchase_intents', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='accounts.peertopeerproduct', verbose_name='Article')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_sale_intents', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': "Intention d'achat",
                'verbose_name_plural': "Intentions d'achat",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('24h', '24 heures'), ('72h', '72 heures'), ('7d', '7 jours')], max_length=10, verbose_name='Durée')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix payé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_boosts', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2c_boosts', to='payments.singpaytransaction', verbose_name='Transaction de paiement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='accounts.peertopeerproduct', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Boost produit',
                'verbose_name_plural': 'Boosts produits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix proposé')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('accepted', 'Acceptée'), ('pending', 'En attente'), ('rejected', 'Refusée'), ('countered', 'Contre-proposition')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='Proposant')),
                ('purchase_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='c2c.purchaseintent', verbose_name="Intention d'achat")),
            ],
            options={
                'verbose_name': 'Négociation',
                'verbose_name_plural': 'Négociations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_code', models.CharField(max_length=6, unique=True, verbose_name='Code vendeur (V-CODE)')),
                ('buyer_code', models.CharField(max_length=6, unique=True, verbose_name='Code acheteur (A-CODE)')),
                ('seller_code_verified', models.BooleanField(default=False, verbose_name='Code vendeur vérifié')),
                ('buyer_code_verified', models.BooleanField(default=False, verbose_name='Code acheteur vérifié')),
                ('seller_code_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification code vendeur')),
                ('buyer_code_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification code acheteur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('seller_code_verified', 'Code vendeur vérifié'), ('buyer_code_verified', 'Code acheteur vérifié'), ('completed', 'Terminé'), ('disputed', 'Litige')], default='pending', max_length=30, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('c2c_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_verification', to='c2c.c2corder', verbose_name='Commande C2C')),
            ],
            options={
                'verbose_name': 'Vérification de livraison',
                'verbose_name_plural': 'Vérifications de livraison',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='c2corder',
            name='purchase_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_order', to='c2c.purchaseintent', verbose_name="Intention d'achat"),
        ),
        migrations.AddField(
            model_name='c2corder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c2c_orders_sold', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
        migrations.CreateModel(
            name='SellerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('new_seller', 'Nouveau Vendeur'), ('good_seller', 'Bon Vendeur'), ('serious_seller', 'Vendeur Sérieux'), ('best_seller', 'Meilleur Vendeur')], max_length=20, verbose_name='Type de badge')),
                ('assignment_type', models.CharField(choices=[('auto', 'Automatique'), ('manual', 'Manuel')], default='auto', max_length=10, verbose_name="Type d'attribution")),
                ('min_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Note minimale')),
                ('min_successful_transactions', models.IntegerField(default=0, verbose_name='Transactions réussies minimales')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2c_badges', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Badge vendeur',
                'verbose_name_plural': 'Badges vendeurs',
                'ordering': ('-assigned_at',),
                'unique_together': {('seller', 'badge_type', 'is_active')},
            },
        ),
        migrations.AddIndex(
            model_name='purchaseintent',
            index=models.Index(fields=['buyer', 'status'], name='c2c_purchas_buyer_i_792069_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseintent',
            index=models.Index(fields=['seller', 'status'], name='c2c_purchas_seller__b85265_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseintent',
            index=models.Index(fields=['product', 'status'], name='c2c_purchas_product_b57026_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseintent',
            unique_together={('product', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='productboost',
            index=models.Index(fields=['product', 'status'], name='c2c_product_product_b08819_idx'),
        ),
        migrations.AddIndex(
            model_name='productboost',
            index=models.Index(fields=['end_date', 'status'], name='c2c_product_end_dat_f931d3_idx'),
        ),
        migrations.AddIndex(
            model_name='c2corder',
            index=models.Index(fields=['buyer', 'status'], name='c2c_c2corde_buyer_i_cff9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='c2corder',
            index=models.Index(fields=['seller', 'status'], name='c2c_c2corde_seller__4abc33_idx'),
        ),
        migrations.AddIndex(
            model_name='c2corder',
            index=models.Index(fields=['status'], name='c2c_c2corde_status_8c76e4_idx'),
        ),
    ]
