# Generated by Django 3.2.14 on 2025-12-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0002_sellerreview'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerreview',
            name='c2c_sellerr_seller__idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerreview',
            name='c2c_sellerr_rating_idx',
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['seller', 'is_visible'], name='c2c_sellerr_seller__3fe000_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['rating'], name='c2c_sellerr_rating_53445f_idx'),
        ),
    ]
