# Generated by Django 3.2.14 on 2025-12-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0004_buyerreview'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='buyerreview',
            name='c2c_buyerre_buyer__idx',
        ),
        migrations.RemoveIndex(
            model_name='buyerreview',
            name='c2c_buyerre_rating_idx',
        ),
        migrations.AddIndex(
            model_name='buyerreview',
            index=models.Index(fields=['buyer', 'is_visible'], name='c2c_buyerre_buyer_i_35f71c_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerreview',
            index=models.Index(fields=['rating'], name='c2c_buyerre_rating_655799_idx'),
        ),
    ]
