# Generated by Django 3.2.14 on 2026-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0006_c2cpaymentevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='c2cpaymentevent',
            name='c2c_c2cpaym_c2c_ord_6b2e8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='c2cpaymentevent',
            name='c2c_c2cpaym_created_8a1f0d_idx',
        ),
        migrations.AddIndex(
            model_name='c2cpaymentevent',
            index=models.Index(fields=['c2c_order', 'event_type'], name='c2c_c2cpaym_c2c_ord_fb0c02_idx'),
        ),
        migrations.AddIndex(
            model_name='c2cpaymentevent',
            index=models.Index(fields=['created_at'], name='c2c_c2cpaym_created_4b5514_idx'),
        ),
    ]
