# Generated by Django 3.2.14 on 2026-03-31 22:26

from django.db import migrations, models
from django.utils import timezone


def backfill_handover_for_existing_verifications(apps, schema_editor):
    DeliveryVerification = apps.get_model('c2c', 'DeliveryVerification')
    now = timezone.now()
    for v in DeliveryVerification.objects.all():
        if v.seller_code_verified or v.buyer_code_verified:
            if not v.buyer_handover_confirmed_at:
                v.buyer_handover_confirmed_at = now
            if not v.seller_handover_confirmed_at:
                v.seller_handover_confirmed_at = now
            v.save(update_fields=['buyer_handover_confirmed_at', 'seller_handover_confirmed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0007_auto_20260218_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryverification',
            name='buyer_handover_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acheteur confirme la réception (étape avant codes)'),
        ),
        migrations.AddField(
            model_name='deliveryverification',
            name='seller_handover_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vendeur confirme la remise (étape avant codes)'),
        ),
        migrations.RunPython(backfill_handover_for_existing_verifications, migrations.RunPython.noop),
    ]
