# Generated by Django 5.1.15 on 2026-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0011_negotiation_expires_at_c2corder_dispute_deadline_disputecase_safezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputecase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='safezone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
