# Generated by Django 5.1.15 on 2026-04-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0013_c2corder_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2corder',
            name='meeting_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude du point de rencontre'),
        ),
        migrations.AddField(
            model_name='c2corder',
            name='meeting_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude du point de rencontre'),
        ),
    ]
