# Generated by Django 5.1.15 on 2026-04-25 03:20

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0014_c2corder_meeting_latitude_c2corder_meeting_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='popular_meeting_min_uses',
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Nombre minimum d'utilisations d'un point personnalisé pour l'afficher en 'Lieu Populaire' (orange) sur la carte.",
                validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)],
                verbose_name='Seuil lieu populaire (usages min)',
            ),
        ),
    ]

