# Base image proche de Ubuntu 22.04
FROM python:3.10-slim

# Variables d'environnement pour pip
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Installer dépendances système
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    gettext \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier requirements
COPY requirements.txt /app/

# Installer Python packages
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

# Copier le reste de l'application
COPY . /app/

# Exposer le port
EXPOSE 8000

# Commande par défaut pour Gunicorn
CMD ["gunicorn", "gabomazone.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
