# Generated by Django 3.2.14 on 2025-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_productsize_name_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDWeight',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDProduct_condition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Neuf'),
        ),
    ]
