# Generated by Django 3.2.14 on 2025-12-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_peer_product_to_order_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_add_view_count_and_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerToPeerOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=13, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('seller_message', models.TextField(blank=True, null=True, verbose_name='Message du vendeur')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_orders_made', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_notifications', to='orders.order', verbose_name='Commande')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_notifications', to='orders.orderdetails', verbose_name='Détail de commande')),
                ('peer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='accounts.peertopeerproduct', verbose_name='Article')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_order_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Notification de commande peer-to-peer',
                'verbose_name_plural': 'Notifications de commande peer-to-peer',
                'ordering': ('-created_at',),
                'unique_together': {('order', 'order_detail', 'peer_product')},
            },
        ),
    ]
