# Generated by Django 3.2.14 on 2025-12-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_productconversation_productmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peertopeerordernotification',
            unique_together=set(),
        ),
    ]
