# Generated by Django 3.2.14 on 2025-12-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_peertopeerordernotification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconversation',
            name='archived_at_buyer',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage (acheteur)"),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='archived_at_seller',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage (vendeur)"),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='is_archived_by_buyer',
            field=models.BooleanField(default=False, verbose_name="Archivé par l'acheteur"),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='is_archived_by_seller',
            field=models.BooleanField(default=False, verbose_name='Archivé par le vendeur'),
        ),
    ]
