# Generated by Django 3.2.14 on 2025-12-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_adminnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peertopeerproduct',
            options={'ordering': ('-date',), 'verbose_name': 'Article C2C', 'verbose_name_plural': 'Articles C2C'},
        ),
        migrations.AlterModelOptions(
            name='peertopeerproductfavorite',
            options={'verbose_name': 'Favori Article C2C', 'verbose_name_plural': 'Favoris Articles C2C'},
        ),
        migrations.RemoveIndex(
            model_name='adminnotification',
            name='accounts_ad_is_read_8a3f2a_idx',
        ),
        migrations.AlterField(
            model_name='peertopeerproductfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.peertopeerproduct', verbose_name='Article C2C'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['is_read', 'is_resolved', 'created_at'], name='accounts_ad_is_read_9e1832_idx'),
        ),
    ]
