# Generated by Django 3.2.14 on 2026-02-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_adminmessage'),
        ('accounts', '0027_vendor_email_verification'),
    ]

    operations = [
    ]
