# Generated by Django 3.2.14 on 2026-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_20260219_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('BOOST_REQUEST', 'Demande de boost'), ('PREMIUM_SUBSCRIPTION', 'Abonnement premium'), ('CONTACT_MESSAGE', 'Message de contact'), ('PRODUCT_APPROVAL', 'Approbation de produit'), ('B2C_PRODUCT_PUBLISHED', 'Nouveau produit B2C en ligne'), ('VENDOR_REGISTRATION', 'Nouveau vendeur B2C inscrit')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
