# Generated by Django 3.2.14 on 2026-03-31 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('BOOST_REQUEST', 'Demande de boost'), ('PREMIUM_SUBSCRIPTION', 'Abonnement premium'), ('CONTACT_MESSAGE', 'Message de contact'), ('PRODUCT_APPROVAL', 'Approbation de produit'), ('B2C_PRODUCT_PUBLISHED', 'Nouveau produit B2C en ligne'), ('VENDOR_REGISTRATION', 'Nouveau vendeur B2C inscrit'), ('CONVERSATION_REPORT', 'Signalement conversation')], max_length=50, verbose_name='Type de notification'),
        ),
        migrations.CreateModel(
            name='ConversationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif court')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', "En cours d'analyse"), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='open', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.productconversation', verbose_name='Conversation')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reports', to=settings.AUTH_USER_MODEL, verbose_name='Auteur du signalement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conversation_reports', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de conversation',
                'verbose_name_plural': 'Signalements de conversation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversationreport',
            index=models.Index(fields=['status', 'created_at'], name='accounts_co_status_2c587a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreport',
            index=models.Index(fields=['reporter', 'created_at'], name='accounts_co_reporte_3cbc07_idx'),
        ),
    ]
